{% set name = "openphase" %}
{% set version = "2.0.0" %}  # replace with actual tagged version

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/ICAMS/OpenPhase.git
  git_tag: v{{ version }}

build:
  number: 0
  skip: true  # [win]  # remove if/when Windows is supported

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]

  host:
    - fftw

  run:
    - fftw

test:
  commands:
    # adapt to an actual installed binary or library
    - test -f $PREFIX/bin/openphase || test -f $PREFIX/lib/libOpenPhase.so  # [unix]

about:
  home: https://github.com/ICAMS/OpenPhase
  summary: "High-performance phase-field simulation framework for materials science"
  description: |
    OpenPhase is a modular, high-performance phase-field simulation framework
    for modeling microstructure evolution in materials science.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - samwaseda
