{% set name = "openphase" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ICAMS/OpenPhase/archive/Release/{{ version }}.tar.gz
  sha256: f91923947afcff4e6b41073954ddc782734ccbfed258985b2f16828f90fa9f8c

build:
  number: 0
  skip: true  # [win]  # remove if/when Windows is supported

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]

  host:
    - fftw

  run:
    - fftw

test:
  commands:
    # adapt to an actual installed binary or library
    - test -f $PREFIX/bin/openphase || test -f $PREFIX/lib/libOpenPhase.so  # [unix]

about:
  home: https://github.com/ICAMS/OpenPhase
  summary: "High-performance phase-field simulation framework for materials science"
  description: |
    OpenPhase is a modular, high-performance phase-field simulation framework
    for modeling microstructure evolution in materials science.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - samwaseda
